# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7541e6ac603b741aed43540bc057ccdeb1d68c6da245eb8d2ad91e4c2f420ff83ae781fdd903ca4058afb6b58edd1298833b5b457de4f6eee0b74a69ba2a89d4

test:
  secret_key_base: d3767274fb4c834e15983401ae2c2cdaebc823e6a9c3a677b9999ba97a1267ac100f8665cc190477adfa074446e8bbfd5d9640526e9bb2f5a179dc66f9159c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
